/*
 * Jakefile
 * PasswordStore
 *
 * Created by You on November 4, 2009.
 * Copyright 2009, Your Company All rights reserved.
 */

var ENV = require("system").env,
    FILE = require("file"),
    task = require("jake").task,
    FileList = require("jake").FileList,
    app = require("cappuccino/jake").app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";

app ("PasswordStore", function(task)
{
    task.setBuildIntermediatesPath(FILE.join("Build", "PasswordStore.build", configuration));
    task.setBuildPath(FILE.join("Build", configuration));

    task.setProductName("PasswordStore");
    task.setIdentifier("com.yourcompany.PasswordStore");
    task.setVersion("1.0");
    task.setAuthor("Your Company");
    task.setEmail("feedback @nospam@ yourcompany.com");
    task.setSummary("PasswordStore");
    task.setSources(new FileList("**/*.j"));
    task.setResources(new FileList("Resources/*"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["PasswordStore"]);
